services:
  app:
    image: snipe/snipe-it:v8.3.5
    restart: unless-stopped
    ports:
      - "${APP_PORT:-8080}:80"
    environment:
      # DOCKER SPECIFIC SETTINGS
      APP_VERSION: v8.3.5
      APP_PORT: "${APP_PORT:-8080}"

      # BASIC APP SETTINGS
      APP_ENV: production
      APP_DEBUG: false
      APP_KEY: "${APP_KEY}"
      APP_URL: "${APP_URL}"
      APP_TIMEZONE: "${APP_TIMEZONE:-Europe/Madrid}"
      APP_LOCALE: "${APP_LOCALE:-en-US}"
      MAX_RESULTS: "${MAX_RESULTS:-500}"
      PHP_UPLOAD_LIMIT: "${PHP_UPLOAD_LIMIT:-20}"
      
      # UPLOADED FILE STORAGE SETTINGS
      PRIVATE_FILESYSTEM_DISK: local
      PUBLIC_FILESYSTEM_DISK: local_public

      # DATABASE SETTINGS
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: '3306'
      DB_DATABASE: "${DB_DATABASE}"
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      DB_PREFIX: null
      DB_DUMP_PATH: /usr/bin
      DB_CHARSET: utf8mb4
      DB_COLLATION: utf8mb4_unicode_ci

      # SSL DATABASE SETTINGS
      DB_SSL: false
      DB_SSL_IS_PAAS: false
      DB_SSL_KEY_PATH: null
      DB_SSL_CERT_PATH: null
      DB_SSL_CA_PATH: null
      DB_SSL_CIPHER: null
      DB_SSL_VERIFY_SERVER: null

      # OUTGOING MAIL SERVER SETTINGS
      MAIL_MAILER: "${MAIL_MAILER:-smtp}"
      MAIL_HOST: "${MAIL_HOST}"
      MAIL_PORT: "${MAIL_PORT:-587}"
      MAIL_USERNAME: "${MAIL_USERNAME}"
      MAIL_PASSWORD: "${MAIL_PASSWORD}"
      MAIL_TLS_VERIFY_PEER: "${MAIL_TLS_VERIFY_PEER:-true}"
      MAIL_FROM_ADDR: "${MAIL_FROM_ADDR}"
      MAIL_FROM_NAME: "${MAIL_FROM_NAME:-Snipe-IT}"
      MAIL_REPLYTO_ADDR: "${MAIL_REPLYTO_ADDR}"
      MAIL_REPLYTO_NAME: "${MAIL_REPLYTO_NAME:-Snipe-IT}"
      MAIL_AUTO_EMBED_METHOD: attachment

      # DATA PROTECTION
      ALLOW_BACKUP_DELETE: false
      ALLOW_DATA_PURGE: false

      # IMAGE LIBRARY
      IMAGE_LIB: gd

      # BACKUP SETTINGS
      MAIL_BACKUP_NOTIFICATION_DRIVER: null
      MAIL_BACKUP_NOTIFICATION_ADDRESS: null
      BACKUP_ENV: true

      # SESSION SETTINGS
      SESSION_LIFETIME: "${SESSION_LIFETIME:-12000}"
      EXPIRE_ON_CLOSE: false
      ENCRYPT: false
      COOKIE_NAME: snipeit_session
      COOKIE_DOMAIN: null
      SECURE_COOKIES: "${SECURE_COOKIES:-false}"
      API_TOKEN_EXPIRATION_YEARS: 40

      # SECURITY HEADER SETTINGS
      # Incluye: redes Docker locales + rangos de Cloudflare
      APP_TRUSTED_PROXIES: 172.16.0.0/12,10.0.0.0/8,173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,108.162.192.0/18,190.93.240.0/20,188.114.96.0/20,197.234.240.0/22,198.41.128.0/17,162.158.0.0/15,104.16.0.0/13,104.24.0.0/14,172.64.0.0/13,131.0.72.0/22
      ALLOW_IFRAMING: false
      REFERRER_POLICY: same-origin
      ENABLE_CSP: false
      CORS_ALLOWED_ORIGINS: null
      ENABLE_HSTS: false

      # CACHE SETTINGS
      CACHE_DRIVER: file
      SESSION_DRIVER: file
      QUEUE_DRIVER: sync
      CACHE_PREFIX: snipeit

      # REDIS SETTINGS
      REDIS_HOST: null
      REDIS_PASSWORD: null
      REDIS_PORT: 6379

      # MEMCACHED SETTINGS
      MEMCACHED_HOST: null
      MEMCACHED_PORT: null

      # PUBLIC S3 Settings
      PUBLIC_AWS_SECRET_ACCESS_KEY: null
      PUBLIC_AWS_ACCESS_KEY_ID: null
      PUBLIC_AWS_DEFAULT_REGION: null
      PUBLIC_AWS_BUCKET: null
      PUBLIC_AWS_URL: null
      PUBLIC_AWS_BUCKET_ROOT: null

      # PRIVATE S3 Settings
      PRIVATE_AWS_ACCESS_KEY_ID: null
      PRIVATE_AWS_SECRET_ACCESS_KEY: null
      PRIVATE_AWS_DEFAULT_REGION: null
      PRIVATE_AWS_BUCKET: null
      PRIVATE_AWS_URL: null
      PRIVATE_AWS_BUCKET_ROOT: null

      # AWS Settings
      AWS_ACCESS_KEY_ID: null
      AWS_SECRET_ACCESS_KEY: null
      AWS_DEFAULT_REGION: null

      # LOGIN THROTTLING
      LOGIN_MAX_ATTEMPTS: 5
      LOGIN_LOCKOUT_DURATION: 60
      RESET_PASSWORD_LINK_EXPIRES: 900

      # MISC
      LOG_CHANNEL: stderr
      LOG_MAX_DAYS: 10
      APP_LOCKED: false
      APP_CIPHER: AES-256-CBC
      APP_FORCE_TLS: false
      GOOGLE_MAPS_API: null
      LDAP_MEM_LIM: 500M
      LDAP_TIME_LIM: 600
    volumes:
      - "${SNIPEIT_STORAGE_PATH}:/var/lib/snipeit"
    depends_on:
      - db

  db:
    image: mariadb:11.5.2
    restart: unless-stopped
    ports:
      - "${DB_PORT:-3306}:3306"
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    volumes:
      - "${SNIPEIT_DB_PATH}:/var/lib/mysql"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 1s
      retries: 5

