# ProxyGPT - Open WebUI + LiteLLM Stack (Docker Swarm)
# https://github.com/open-webui/open-webui + https://github.com/BerriAI/litellm
#
# This stack file sets up a complete ProxyGPT stack with:
# - Open WebUI: Web interface for interacting with LLMs (Port 8088)
# - LiteLLM: LLM proxy server with model management (Port 4000)
# - PostgreSQL: Database for LiteLLM (Internal port 5432)
#
# Open WebUI is integrated with LiteLLM for unified LLM access and can also
# connect directly to Ollama servers via OLLAMA_BASE_URL.
#
# ===========================================
# DEPLOYMENT STEPS:
# ===========================================
# 1. Create required directories on Swarm manager node:
#    sudo mkdir -p /mnt/cephfs/proxy-gpt/{litellm-db,open-webui-data}
#    sudo chown -R 1000:1000 /mnt/cephfs/proxy-gpt
# 2. Generate secure keys (see STEP 1 below)
# 3. Configure environment variables in Portainer Swarm stack
# 4. Deploy the stack
#
# ===========================================
# SECURITY OPTIONS (Choose one approach):
# ===========================================
#
# ===========================================
# CONFIGURATION OPTIONS:
# ===========================================
#
# Option 1 - Individual Environment Variables (Recommended):
# Configure each component separately in Portainer Swarm stack
#
# Option 2 - Docker Secrets (Most secure for production):
# echo "postgresql://llmproxy:your_secure_password@db:5432/litellm" > database_url.txt
# echo "litellm" > postgres_db.txt
# echo "llmproxy" > postgres_user.txt
# echo "your_secure_password" > postgres_password.txt
# echo "sk-your-master-key" > master_key.txt
# echo "sk-your-salt-key" > salt_key.txt
# docker secret create database_url database_url.txt
# docker secret create postgres_db postgres_db.txt
# docker secret create postgres_user postgres_user.txt
# docker secret create postgres_password postgres_password.txt
# docker secret create litellm_master_key master_key.txt
# docker secret create litellm_salt_key salt_key.txt
# rm *.txt
#
# ===========================================
# REQUIRED ENVIRONMENT VARIABLES (Configure in Portainer Stack):
# ===========================================
# ⚠️  IMPORTANT: In Portainer, DO NOT use quotes around variable values!
# ⚠️  Example: DATABASE_URL=postgresql://... (WITHOUT quotes)
#
# - OLLAMA_BASE_URL: URL of your Ollama server (e.g., http://10.0.1.11:11434)
# - DATABASE_URL: Complete PostgreSQL connection string
#   Format: postgresql://USER:PASSWORD@db:5432/DATABASE_NAME
#   Example: postgresql://llmproxy:your_secure_password@db:5432/litellm
# - LITELLM_MASTER_KEY: Master key for LiteLLM authentication (GENERATE FIRST!)
# - LITELLM_SALT_KEY: Salt key for LiteLLM encryption (GENERATE FIRST!)
# - POSTGRES_DB: PostgreSQL database name (e.g., litellm)
# - POSTGRES_USER: PostgreSQL username (e.g., llmproxy)
# - POSTGRES_PASSWORD: PostgreSQL password (REQUIRED)
#
# Optional variables (with defaults):
# - LITELLM_DATA_PATH: Path for PostgreSQL data (default: /mnt/cephfs/proxy-gpt/litellm-db)
# - OPENWEBUI_DATA_PATH: Path for Open WebUI data (default: /mnt/cephfs/proxy-gpt/open-webui-data)
#
# ===========================================
# STEP 1: Generate Secure Keys and Configure Variables (REQUIRED)
# ===========================================
# Execute these commands in your terminal BEFORE deploying:
#
# 1. Generate LITELLM_MASTER_KEY:
#   echo "sk-$(openssl rand -hex 24)"
#
# 2. Generate LITELLM_SALT_KEY:
#   echo "sk-$(openssl rand -hex 24)"
#
# Example output:
#   sk-a1b2c3d4e5f6789abc012def34567890abcdef1234567890ab
#   sk-z9y8x7w6v5u43210fedcba9876543210fedcba0987654321
#
# 3. Configure DATABASE_URL:
#   IMPORTANT: The DATABASE_URL must match your PostgreSQL credentials.
#   Format: postgresql://POSTGRES_USER:POSTGRES_PASSWORD@db:5432/POSTGRES_DB
#
#   Example configuration in Portainer:
#   POSTGRES_USER=llmproxy
#   POSTGRES_PASSWORD=your_secure_password_here
#   POSTGRES_DB=litellm
#   DATABASE_URL=postgresql://llmproxy:your_secure_password_here@db:5432/litellm
#
#   Note: The username, password, and database name in DATABASE_URL MUST match
#   the values in POSTGRES_USER, POSTGRES_PASSWORD, and POSTGRES_DB respectively.
#
# Save these values - you'll need them for Portainer Swarm stack variables!
#
# ===========================================
# DEPLOYMENT INSTRUCTIONS:
# ===========================================
# Deploy with: docker stack deploy -c proxy-gpt-swarm.yaml proxygpt
#
# Or using Portainer:
# 1. Go to Stacks > Add stack
# 2. Upload this file or paste its contents
# 3. Add environment variables in the "Environment variables" section
#    IMPORTANT: Do NOT use quotes around values!
#    Example format in Portainer:
#    
#    Name                 | Value
#    ---------------------|-----------------------------------------------
#    OLLAMA_BASE_URL      | http://10.0.1.11:11434
#    DATABASE_URL         | postgresql://llmproxy:password@db:5432/litellm
#    POSTGRES_DB          | litellm
#    POSTGRES_USER        | llmproxy
#    POSTGRES_PASSWORD    | password
#    LITELLM_MASTER_KEY   | sk-your-generated-key
#    LITELLM_SALT_KEY     | sk-your-generated-salt-key
#
# 4. Click "Deploy the stack"
#
# ===========================================
# TROUBLESHOOTING:
# ===========================================
# - Check stack status: docker stack ps proxygpt
# - View service logs: docker service logs proxygpt_<service_name>
#   Example: docker service logs proxygpt_litellm -f
# - Check if all services are running: docker stack services proxygpt
#
# Common Issues:
# --------------
# 1. Database connection issues:
#   * Error: "URL must start with postgresql://"
#     → Remove quotes from DATABASE_URL in Portainer
#   * Verify DATABASE_URL is set correctly
#   * Format: postgresql://USER:PASSWORD@db:5432/DATABASE_NAME
#   * Ensure POSTGRES_DB, POSTGRES_USER, POSTGRES_PASSWORD match DATABASE_URL
#   * Ensure db service is healthy before litellm starts
#   * Check db healthcheck: docker service logs proxygpt_db -f
#
# 2. Healthcheck issues (Container shows "Complete" status):
#   * Error in logs: "HEAD /health/liveliness HTTP/1.1" 405 Method Not Allowed
#     → Healthcheck uses GET method, not HEAD (fixed in current version)
#   * Check healthcheck status: docker service ps proxygpt_litellm
#   * Verify endpoint is responding: curl http://localhost:4000/health/liveliness
#
# 3. Volume permission issues:
#   * Ensure directories exist: /mnt/cephfs/proxy-gpt/litellm-db and /mnt/cephfs/proxy-gpt/open-webui-data
#   * Check permissions: sudo chown -R 1000:1000 /mnt/cephfs/proxy-gpt
#
# 4. All services use 'node.role == manager' constraint for co-location
# 5. Verify environment variables: docker service inspect proxygpt_litellm --pretty
# ===========================================

version: '3.8'

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    networks:
      - proxygpt
    depends_on:
      - litellm
    volumes:
      - open-webui-data:/app/backend/data
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
    ports:
      - "8088:8080"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
      placement:
        constraints:
          - node.role == manager

  litellm:
    image: ghcr.io/berriai/litellm:main-stable
    networks:
      - proxygpt
    depends_on:
      - db
    # Uncomment the secrets section below if using Docker Secrets instead of environment variables
    # secrets:
    #   - database_url
    #   - litellm_master_key
    #   - litellm_salt_key
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - STORE_MODEL_IN_DB=True
      - LITELLM_MASTER_KEY=${LITELLM_MASTER_KEY}
      - LITELLM_SALT_KEY=${LITELLM_SALT_KEY}
    ports:
      - "4000:4000"
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 -O /dev/null http://localhost:4000/health/liveliness || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
      placement:
        constraints:
          - node.role == manager

  db:
    image: postgres:16
    networks:
      - proxygpt
    # Uncomment the secrets section below if using Docker Secrets instead of environment variables
    # secrets:
    #   - postgres_db
    #   - postgres_user
    #   - postgres_password
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - litellm-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
      placement:
        constraints:
          - node.role == manager

volumes:
  open-webui-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${OPENWEBUI_DATA_PATH:-/mnt/cephfs/proxy-gpt/open-webui-data}
  litellm-db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${LITELLM_DATA_PATH:-/mnt/cephfs/proxy-gpt/litellm-db}

networks:
  proxygpt:
    driver: overlay

# Uncomment the secrets section below if using Docker Secrets
# secrets:
#   database_url:
#     external: true
#   postgres_db:
#     external: true
#   postgres_user:
#     external: true
#   postgres_password:
#     external: true
#   litellm_master_key:
#     external: true
#   litellm_salt_key:
#     external: true
#
# ===========================================
# EXAMPLE PORTAINER ENVIRONMENT VARIABLES CONFIGURATION
# ===========================================
# Copy and paste these into Portainer's "Environment variables" section
# when deploying the stack. Replace the example values with your actual values.
#
# ⚠️  CRITICAL: DO NOT USE QUOTES around the values in Portainer!
# ⚠️  Quotes will be included literally and cause connection errors.
#
# REQUIRED VARIABLES:
# -------------------
# OLLAMA_BASE_URL=http://192.168.1.110:11434
# DATABASE_URL=postgresql://llmproxy:your_secure_password_here@db:5432/litellm
# LITELLM_MASTER_KEY=sk-a1b2c3d4e5f6789abc012def34567890abcdef1234567890ab
# LITELLM_SALT_KEY=sk-z9y8x7w6v5u43210fedcba9876543210fedcba0987654321
# POSTGRES_DB=litellm
# POSTGRES_USER=llmproxy
# POSTGRES_PASSWORD=your_secure_password_here
#
# OPTIONAL VARIABLES (uncomment if needed):
# -----------------------------------------
# LITELLM_DATA_PATH=/mnt/cephfs/proxy-gpt/litellm-db
# OPENWEBUI_DATA_PATH=/mnt/cephfs/proxy-gpt/open-webui-data
#
# IMPORTANT NOTES:
# ----------------
# 1. DO NOT use quotes (", ') around values - they will be included literally!
#    ❌ WRONG: DATABASE_URL="postgresql://..."
#    ✅ RIGHT: DATABASE_URL=postgresql://...
#
# 2. Ensure POSTGRES_USER, POSTGRES_PASSWORD, and POSTGRES_DB in DATABASE_URL
#    match the individual POSTGRES_* variables exactly
#
# 3. Generate secure keys before deploying (see STEP 1 above)
#
# 4. Keep your keys and passwords secure - never commit them to version control
#
# 5. Common errors:
#    - "URL must start with postgresql://" → Remove quotes from DATABASE_URL
#    - "Connection refused" → Check POSTGRES_PASSWORD matches in both variables
#    - "Database does not exist" → Verify POSTGRES_DB matches DATABASE_URL
# ===========================================
