services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v2.8.0
    container_name: mealie
    restart: always
    ports:
      - "9925:9000"
    deploy:
      resources:
        limits:
          memory: 1000M
    volumes:
      - /home/notolac/mealie:/app/data/
    environment:
      # Set Backend ENV Variables Here
      ALLOW_SIGNUP: false
      PUID: 1000
      PGID: 1000
      TZ: Europe/Madrid
      MAX_WORKERS: 1
      WEB_CONCURRENCY: 2
      BASE_URL: $BASE_URL # https://mealie.example.com
      SMTP_HOST: $SMTP_HOST
      SMTP_PORT: $SMTP_PORT
      SMTP_FROM_NAME: $SMTP_FROM_NAME
      SMTP_AUTH_STRATEGY: $SMTP_AUTH_STRATEGY
      SMTP_FROM_EMAIL: $SMTP_FROM_EMAIL
      SMTP_USER: $SMTP_USER
      SMTP_PASSWORD: $SMTP_PASSWORD