---
services:
  jdownloader-2:
    image: jlesage/jdownloader-2
    ports:
      - "$HOST_PORT:5800"
    volumes:
      - "${JDOWNLOADER_CONFIG_PATH:-/opt/jdownloader}:/config:rw"
      - "${JDOWNLOADER_OUTPUT_PATH:-/data/downloads}:/output:rw"
