---
version: '3'
services:
  jdownloader-2:
    image: jlesage/jdownloader-2
    ports:
      - "5800:5800"
    volumes:
      - "/docker/appdata/jdownloader-2:/config:rw"
      - "/mnt/Jdownload:/output:rw"