---
services:
  jdownloader-2:
    image: jlesage/jdownloader-2
    ports:
      - "$HOST_PORT:5800"
    volumes:
      - "/home/notolac/jdownloader:/config:rw"
      - "/storage_hdd/jdownloads-output:/output:rw"
