---
services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: unless-stopped
    ports:
      - "${N8N_HTTP_PORT:-5678}:${N8N_PORT:-5678}"
    environment:
      - N8N_HOST=${N8N_HOST}
      - N8N_PORT=${N8N_PORT:-5678}
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - WEBHOOK_URL=${WEBHOOK_URL}
      - GENERIC_TIMEZONE=Europe/Madrid
      - N8N_SECURE_COOKIE=true
    volumes:
      - ${N8N_DATA_DIR:-/srv/n8n}:/home/node/.n8n