version: '3.8'

services:
  vaultwarden:
    image: vaultwarden/server:latest
    networks:
      - vaultwarden-net
    volumes:
      - vaultwarden-data:/data
    ports:
      - "${VAULTWARDEN_PORT:-8080}:80"
    environment:
      - SMTP_HOST=${SMTP_HOST:-smtp.office365.com}
      - SMTP_FROM=${SMTP_FROM}
      - SMTP_FROM_NAME=${SMTP_FROM_NAME}
      - SMTP_SECURITY=${SMTP_SECURITY:-starttls}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_TIMEOUT=${SMTP_TIMEOUT:-30}
      - SMTP_AUTH_MECHANISM=${SMTP_AUTH_MECHANISM:-Plain,Login}
      - LOGIN_RATELIMIT_MAX_BURST=${LOGIN_RATELIMIT_MAX_BURST:-10}
      - LOGIN_RATELIMIT_SECONDS=${LOGIN_RATELIMIT_SECONDS:-60}
      - DOMAIN=${DOMAIN}
      - INVITATION_ORG_NAME=${INVITATION_ORG_NAME}
      - INVITATIONS_ALLOWED=${INVITATIONS_ALLOWED:-true}
      - ADMIN_TOKEN=${ADMIN_TOKEN}
      - SIGNUPS_ALLOWED=${SIGNUPS_ALLOWED:-true}
      - SIGNUPS_DOMAINS_WHITELIST=${SIGNUPS_DOMAINS_WHITELIST}
      - SIGNUPS_VERIFY=${SIGNUPS_VERIFY:-true}
      - SIGNUPS_VERIFY_RESEND_TIME=${SIGNUPS_VERIFY_RESEND_TIME:-3600}
      - SIGNUPS_VERIFY_RESEND_LIMIT=${SIGNUPS_VERIFY_RESEND_LIMIT:-6}
      - EMERGENCY_ACCESS_ALLOWED=${EMERGENCY_ACCESS_ALLOWED:-true}
      - SENDS_ALLOWED=${SENDS_ALLOWED:-true}
      - WEB_VAULT_ENABLED=${WEB_VAULT_ENABLED:-true}
      - ROCKET_ADDRESS=${ROCKET_ADDRESS:-0.0.0.0}
      - ROCKET_PORT=${ROCKET_PORT:-80}
      - IP_HEADER=${IP_HEADER:-X-Forwarded-For}
      - ICON_BLACKLIST_NON_GLOBAL_IPS=${ICON_BLACKLIST_NON_GLOBAL_IPS:-false}
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
      placement:
        constraints:
          - node.role == manager

networks:
  vaultwarden-net:
    driver: overlay
    attachable: true

volumes:
  vaultwarden-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${VAULTWARDEN_DATA_PATH:-/mnt/cephfs/vaultwarden}

