services:
  guacd:
    image: guacamole/guacd
    container_name: guacd
    networks:
      - guacnet
    ports:
      - "4822:4822"

  mysql-guacamole:
    image: mysql:8.0
    container_name: guacamoledb
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - guacnet

  guacamole:
    image: guacamole/guacamole
    container_name: guacamole-oficial
    depends_on:
      - guacd
      - mysql-guacamole
    environment:
      MYSQL_HOSTNAME: "mysql-guacamole" # Hostname del contenedor mysql
      MYSQL_PORT: "3306" # Puerto estándar de PostgreSQL
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      GUACD_HOSTNAME: "guacd" # Hostname del contenedor guacd
      GUACD_PORT: "4822" # Puerto estándar de guacd
      TOTP_ENABLED: "true"
    ports:
      - "$HOSTPORT:8080"
    networks:
      - guacnet

networks:
  guacnet:
    driver: bridge

volumes:
  mysql_data:
