---
services:
  guacd:
    image: guacamole/guacd:1.6.0
    container_name: guacd
    networks: [guacnet]

  mysql-guacamole:
    image: mysql:8.0
    container_name: guacamoledb
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - /home/notolac/guacamole-mysql:/var/lib/mysql
    networks: [guacnet]

  guacamole:
    image: guacamole/guacamole:1.6.0
    container_name: guacamole-oficial
    depends_on:
      guacd:
        condition: service_started
      mysql-guacamole:
        condition: service_started
    environment:
      MYSQL_HOSTNAME: "mysql-guacamole"
      MYSQL_PORT: "3306"
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      GUACD_HOSTNAME: "guacd"
      GUACD_PORT: "4822"
      TOTP_ENABLED: "true"
    networks:
      - guacnet
      - traefik-stack
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.guac.rule=Host(`${GUAC_DOMAIN}`) && PathPrefix(`/guacamole`)"
      - "traefik.http.routers.guac.entrypoints=websecure"
      - "traefik.http.routers.guac.tls=true"
      - "traefik.http.routers.guac.tls.certresolver=cloudflare"
      - "traefik.http.routers.guac.service=guac-svc"
      - "traefik.http.services.guac-svc.loadbalancer.server.port=8080"
      - "traefik.http.services.guac-svc.loadbalancer.passHostHeader=true"




networks:
  guacnet:
    driver: bridge
  traefik-stack:
    external: true
