version: '3.8'

services:
  wallos:
    image: bellamy/wallos:latest
    networks:
      - wallos-network
    volumes:
      - wallos-db:/var/www/html/db
      - wallos-logos:/var/www/html/images/uploads/logos
    ports:
      - "${WALLOS_PORT:-8282}:80/tcp"
    environment:
      # Zona horaria
      TZ: "Europe/Madrid"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
      placement:
        constraints:
          - node.role == manager

networks:
  wallos-network:
    driver: overlay
    attachable: true

volumes:
  wallos-db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${WALLOS_DATA_PATH:-/mnt/cephfs/wallos-app/db}
  wallos-logos:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${WALLOS_LOGOS_PATH:-/mnt/cephfs/wallos-app/logos}
