---
services:
  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: speedtest-tracker
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - APP_KEY=${APP_KEY}
      - DB_CONNECTION=sqlite
      - SPEEDTEST_SCHEDULE=${SPEEDTEST_SCHEDULE}
      - SPEEDTEST_SERVERS=
      - DB_HOST= #optional
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DISPLAY_TIMEZONE=Europe/Madrid #optional
      - PRUNE_RESULTS_OLDER_THAN=0 #optional
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    volumes:
      - ${SPEEDTEST_TRACKER_DATA_PATH}:/config
    ports:
      - ${SPEEDTEST_TRACKER_PORT:-80}:80
    restart: unless-stopped
