---
services:
  coolify:
    image: "${REGISTRY_URL:-ghcr.io}/coollabsio/coolify:${LATEST_IMAGE:-latest}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - type: bind
        source: /home/coolify/source/.env
        target: /var/www/html/.env
        read_only: true
      - /home/coolify/ssh:/var/www/html/storage/app/ssh
      - /home/coolify/applications:/var/www/html/storage/app/applications
      - /home/coolify/databases:/var/www/html/storage/app/databases
      - /home/coolify/services:/var/www/html/storage/app/services
      - /home/coolify/backups:/var/www/html/storage/app/backups
      - /home/coolify/webhooks-during-maintenance:/var/www/html/storage/app/webhooks-during-maintenance
    environment:
      - APP_ENV=${APP_ENV:-production}
      - PHP_MEMORY_LIMIT=${PHP_MEMORY_LIMIT:-256M}
      - PHP_FPM_PM_CONTROL=${PHP_FPM_PM_CONTROL:-dynamic}
      - PHP_FPM_PM_START_SERVERS=${PHP_FPM_PM_START_SERVERS:-1}
      - PHP_FPM_PM_MIN_SPARE_SERVERS=${PHP_FPM_PM_MIN_SPARE_SERVERS:-1}
      - PHP_FPM_PM_MAX_SPARE_SERVERS=${PHP_FPM_PM_MAX_SPARE_SERVERS:-10}
    # Publicado al host
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL","curl -fsS http://127.0.0.1:8080/api/health || exit 1"]
      interval: 5s
      retries: 10
      timeout: 2s
    depends_on:
      coolify-db:
        condition: service_healthy
      coolify-redis:
        condition: service_healthy
      soketi:
        condition: service_healthy

  coolify-db:
    image: postgres:15
    environment:
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_DATABASE:-coolify}"
    volumes:
      - type: bind
        source: /home/coolify/databases/postgres
        target: /var/lib/postgresql/data
    healthcheck:
      test: ["CMD","pg_isready","-U","${DB_USERNAME}","-d","${DB_DATABASE:-coolify}"]
      interval: 5s
      retries: 10
      timeout: 2s

  coolify-redis:
    image: redis:7
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    environment:
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
    volumes:
      - type: bind
        source: /home/coolify/databases/redis
        target: /data
    healthcheck:
      test: ["CMD-SHELL","redis-cli -a \"$REDIS_PASSWORD\" -h 127.0.0.1 ping | grep -q PONG"]
      interval: 5s
      retries: 10
      timeout: 2s

  soketi:
    image: '${REGISTRY_URL:-ghcr.io}/coollabsio/coolify-realtime:1.0.10'
    volumes:
      - /home/coolify/ssh:/var/www/html/storage/app/ssh
    environment:
      APP_NAME: "${APP_NAME:-Coolify}"
      SOKETI_DEBUG: "${SOKETI_DEBUG:-false}"
      SOKETI_DEFAULT_APP_ID: "${PUSHER_APP_ID}"
      SOKETI_DEFAULT_APP_KEY: "${PUSHER_APP_KEY}"
      SOKETI_DEFAULT_APP_SECRET: "${PUSHER_APP_SECRET}"
      SOKETI_HOST: 0.0.0.0 
    # Publica el puerto WS; deja 6002 interno (readiness/metrics)
    ports:
      - "6001:6001"
      - "6002:6002"

    healthcheck:
      test: ["CMD-SHELL","wget -qO- http://127.0.0.1:6001/ready >/dev/null && wget -qO- http://127.0.0.1:6002/ready >/dev/null || exit 1"]
      interval: 5s
      retries: 10
      timeout: 2s
