services:
  #app:
  #  image: "docker.io/jc21/nginx-proxy-manager:latest"
  #  container_name: nginx-proxy
  #  restart: always
  #  ports:
  #    - 8080:80
  #    - 8181:81
  #    - 443:443
  #  volumes:
  #    - data:/data
  #    - letsencrypt:/etc/letsencrypt
  #    - /home/notolac/nginx-proxy-manager/_hsts.conf:/app/templates/_hsts.conf:ro

  goaccess:
    image: "xavierh/goaccess-for-nginxproxymanager:latest"
    container_name: goaccess
    restart: always
    ports:
      - "7880:7880"
    environment:
      - TZ=Europe/Madrid
      - SKIP_ARCHIVED_LOGS=False #optional
      - DEBUG=False #optional
      - BASIC_AUTH=False #optional
      - BASIC_AUTH_USERNAME= #optional
      - BASIC_AUTH_PASSWORD= #optional
      - EXCLUDE_IPS=127.0.0.1 #optional - comma delimited
      - LOG_TYPE=NPM #optional - more information below
      - ENABLE_BROWSERS_LIST=True #optional - more information below
      - CUSTOM_BROWSERS=Kuma:Uptime,TestBrowser:Crawler #optional - comma delimited, more information below
      - HTML_REFRESH=5 #optional - Refresh the HTML report every X seconds. https://goaccess.io/man
      - KEEP_LAST=90 #optional - Keep the last specified number of days in storage. https://goaccess.io/man
      - PROCESSING_THREADS=1 # optional - number of concurrent processing threads; default 1
    volumes:
      #- /home/notolac/nginx-proxy-manager/data/logs:/opt/log:ro #required - path to your Nginx Proxy Manager logs
      - /home/notolac/traefik-stack/traefik/logs:/opt/custom #optional, required if using log_type = CUSTOM #change to the location of your choice

#volumes:
#  data:
#    driver: local
#    driver_opts:
#      type: none
#      o: bind
#      device: /home/notolac/nginx-proxy-manager/data
#  letsencrypt:
#    driver: local
#    driver_opts:
#      type: none
#      o: bind
#      device: /home/notolac/nginx-proxy-manager/letsencrypt
