services:
  rclone_sync:
    image: rclone/rclone:latest
    container_name: rclone_sync
    volumes:
      - /home/notolac/.config/rclone/rclone.conf:/config/rclone/rclone.conf:ro
      - /home/notolac/scripts/rclone_entrypoint_backup.sh:/backup.sh:ro
      - /home/notolac/scripts/rclone_entrypoint_restore.sh:/restore.sh:ro
      - /storage_hdd/multimedia:/data/multimedia
      - /media/Plex:/data/Plex
    entrypoint: ["/bin/sh", "-c", "/$RCLONE_SCRIPT.sh"]
    environment:
      - RCLONE_CONFIG=/config/rclone/rclone.conf
    restart: unless-stopped
