---
services:
  mysql:
    restart: unless-stopped
    image: mysql:8.0
    hostname: mysql
    volumes:
      - semaphore-mysql:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: semaphoreui
      MYSQL_USER: semaphore
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - semaphornet

  semaphore:
    restart: unless-stopped
    container_name: ansiblesemaphore
    image: semaphoreui/semaphore:latest
    ports:
      - $HOST_PORT:3000
    environment:
      SEMAPHORE_DB_USER: semaphore
      SEMAPHORE_DB_PASS: $SEMAPHORE_DB_PASS
      SEMAPHORE_DB_HOST: mysql # for postgres, change to: postgres
      SEMAPHORE_DB_PORT: 3306 # change to 5432 for postgres
      SEMAPHORE_DB_DIALECT: mysql # for postgres, change to: postgres
      SEMAPHORE_DB: semaphoreui
      SEMAPHORE_PLAYBOOK_PATH: /tmp/semaphore/
      SEMAPHORE_ADMIN_PASSWORD: $SEMAPHORE_ADMIN_PASSWORD
      SEMAPHORE_ADMIN_NAME: admin
      SEMAPHORE_ADMIN_EMAIL: $SEMAPHORE_ADMIN_EMAIL
      SEMAPHORE_ADMIN: $SEMAPHORE_ADMIN
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: $SEMAPHORE_ACCESS_KEY_ENCRYPTION
      TZ: Europe/Madrid
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - semaphornet
volumes:
  semaphore-mysql: # to use postgres, switch to: semaphore-postgres

networks:
  semaphornet:
    driver: bridge
