services:
  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptime-kuma
    volumes:
      - /home/notolac/uptime-kuma:/app/data
    ports:
      - $HOST_PORT:3001 # <Host Port>:<Container Port>
    restart: always

