version: "3.8"

services:
  photoprism:
    image: photoprism/photoprism:latest
    restart: unless-stopped
    stop_grace_period: 10s
    depends_on:
      - mariadb
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    ports:
      - "2342:2342" # HTTP port (host:container)
    environment:
      PHOTOPRISM_ADMIN_USER: "$PHOTOPRISM_ADMIN_USER"
      PHOTOPRISM_ADMIN_PASSWORD: "$PHOTOPRISM_ADMIN_PASSWORD"
      PHOTOPRISM_AUTH_MODE: "password"
      PHOTOPRISM_SITE_URL: "http://localhost:2342/"
      PHOTOPRISM_DISABLE_TLS: "false"
      PHOTOPRISM_DEFAULT_TLS: "true"
      PHOTOPRISM_ORIGINALS_LIMIT: 5000
      PHOTOPRISM_HTTP_COMPRESSION: "gzip"
      PHOTOPRISM_LOG_LEVEL: "info"
      PHOTOPRISM_READONLY: "false"
      PHOTOPRISM_EXPERIMENTAL: "false"
      PHOTOPRISM_DISABLE_CHOWN: "false"
      PHOTOPRISM_DISABLE_WEBDAV: "false"
      PHOTOPRISM_DISABLE_SETTINGS: "false"
      PHOTOPRISM_DISABLE_TENSORFLOW: "false"
      PHOTOPRISM_DISABLE_FACES: "false"
      PHOTOPRISM_DISABLE_CLASSIFICATION: "false"
      PHOTOPRISM_DISABLE_VECTORS: "false"
      PHOTOPRISM_DISABLE_RAW: "false"
      PHOTOPRISM_RAW_PRESETS: "false"
      PHOTOPRISM_JPEG_QUALITY: 85
      PHOTOPRISM_DETECT_NSFW: "false"
      PHOTOPRISM_UPLOAD_NSFW: "true"
      PHOTOPRISM_DATABASE_DRIVER: "mysql"
      PHOTOPRISM_DATABASE_SERVER: "mariadb:3306"
      PHOTOPRISM_DATABASE_NAME: "photoprism"
      PHOTOPRISM_DATABASE_USER: "$PHOTOPRISM_DATABASE_USER"
      PHOTOPRISM_DATABASE_PASSWORD: "$PHOTOPRISM_DATABASE_PASSWORD"
      PHOTOPRISM_SITE_CAPTION: "CasRom Photos App"
      PHOTOPRISM_SITE_DESCRIPTION: ""
      PHOTOPRISM_SITE_AUTHOR: ""

      # Configuración para usar NVIDIA GPU
      PHOTOPRISM_FFMPEG_ENCODER: "nvidia"               # usar el encoder NVIDIA H.264 :contentReference[oaicite:0]{index=0}
      PHOTOPRISM_FFMPEG_SIZE: "1920"
      PHOTOPRISM_FFMPEG_BITRATE: "32"
      PHOTOPRISM_INIT: "tensorflow-gpu"                 # instala TensorFlow GPU-optimizado :contentReference[oaicite:1]{index=1}
      NVIDIA_VISIBLE_DEVICES: "all"                     # permite acceso a todas las GPUs :contentReference[oaicite:2]{index=2}
      NVIDIA_DRIVER_CAPABILITIES: "all"                 # expone todas las capacidades GPU :contentReference[oaicite:3]{index=3}

    deploy:
      resources:
        reservations:
          devices:
            - driver: "nvidia"
              capabilities: [gpu]
              count: 1                                # reserva 1 GPU NVIDIA :contentReference[oaicite:4]{index=4}

    working_dir: "/photoprism"
    volumes:
      - "/srv/multimedia/PhotoPrism-fotos:/photoprism/originals"
      - "/storage_hdd/photoprism-import:/photoprism/import"
      - "/home/notolac/.tmp/PhotoPrism-cache:/photoprism/storage"

  mariadb:
    image: mariadb:11
    restart: unless-stopped
    stop_grace_period: 5s
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    command: >
      --innodb-buffer-pool-size=512M
      --transaction-isolation=READ-COMMITTED
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --max-connections=512
      --innodb-rollback-on-timeout=OFF
      --innodb-lock-wait-timeout=120
    volumes:
      - "/home/notolac/photoprisma/database:/var/lib/mysql"
    environment:
      MARIADB_AUTO_UPGRADE: "1"
      MARIADB_INITDB_SKIP_TZINFO: "1"
      MARIADB_DATABASE: "photoprism"
      MARIADB_USER: "$MARIADB_USER"
      MARIADB_PASSWORD: "$MARIADB_PASSWORD"
      MARIADB_ROOT_PASSWORD: "$MARIADB_ROOT_PASSWORD"
